// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.Models;

namespace Project2.Migrations.ImageDb
{
    [DbContext(typeof(ImageDbContext))]
    partial class ImageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project2.Models.ImageModel", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("capturedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("capturedDate")
                        .HasColumnType("date");

                    b.Property<string>("geoloaction")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("imageFileName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tag")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("imageId");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
